export const BLOG_ACTION_TYPES = {
  ADD_BLOG: "blog/ADD_BLOG",
  FETCH_BLOG_START: "blog/FETCH_BLOG_START",
  FETCH_BLOG_SUCCESS: "blog/FETCH_BLOG_SUCCESS",
  FETCH_BLOG_FAILED: "blog/FETCH_BLOG_FAILED",
  DELTE_BLOG_START: "blog/DELTE_BLOG_START",
  DELTE_BLOG_SUCCESS: "blog/DELTE_BLOG_SUCCESS",
  DELTE_BLOG_FAILED: "blog/DELTE_BLOG_FAILED",
};
