export const BLOG_ACTION_TYPES = {
  FETCH_BLOG_START: "blog/FETCH_BLOG_START",
  FETCH_BLOG_SUCCESS: "blog/FETCH_BLOG_SUCCESS",
  FETCH_BLOG_FAILED: "blog/FETCH_BLOG_FAILED",
  DELETE_BLOG_START: "blog/DELETE_BLOG_START",
  DELETE_BLOG_SUCCESS: "blog/DELETE_BLOG_SUCCESS",
  DELETE_BLOG_FAILED: "blog/DELETE_BLOG_FAILED",
};
